spring:
  security:
    oauth2:
      client:
        registration:
          google-client:
            client-id: 924454274973-ognkbbc2obvmr9clerqua26pjrphgv4q.apps.googleusercontent.com
            client-secret: 2kAIXFZtyfwyBbMHTCkZ8QOr
            client-name: google user
            provider: google
            scope: profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8080