spring:
  security:
    oauth2:
      client:
        registration:
          google-client:
            client-id: 924454274973-ognkbbc2obvmr9clerqua26pjrphgv4q.apps.googleusercontent.com
            client-secret: 2kAIXFZtyfwyBbMHTCkZ8QOr
            client-name: google user
            provider: google
            scope: profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  datasource:
    url: jdbc:mysql://localhost/musicstore
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
file:
  upload-dir: storage
